-- Tour Package Analyzer: realistic test cases for analysis + recommendation engine
-- Creates a Travel Pro agency, an OWNER user, and all related package test cases.
-- Run in PostgreSQL after migrations are applied.
-- UI login for functional testing:
--   email: travelpro.owner@example.com
--   password: password
-- After running this script, call POST /tour-packages/:uuid/analyze for each package UUID printed at the end.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
DECLARE
    -- Seeded UI test account:
    -- email: travelpro.owner@example.com
    -- password: password
    -- password hash is generated by PostgreSQL pgcrypto bcrypt so it matches backend bcrypt.compare()
    v_owner_email text := 'travelpro.owner@example.com';
    v_owner_username text := 'travelpro_owner';
    v_owner_password text := 'password';
    v_owner_password_hash text := crypt(v_owner_password, gen_salt('bf', 10));

    -- Seeded tenant:
    -- agency uuid: 8a17068c-539a-4ddf-8302-47a6a2c60c92 / slug: travel-pro
    -- user uuid: 9c537ec2-1f1f-4096-bb6e-26a85bd50a72
    v_owner_user_id int;
    v_agency_id int;
    v_pkg int;
    d1 int; d2 int; d3 int; d4 int; d5 int;
    s_hotel_a int; s_hotel_b int; s_transport int; s_guide int; s_activity int; s_meal int; s_other int; s_luxury int;
BEGIN
    -- Create or update the Travel Pro tenant used by all test cases.
    INSERT INTO agencies (uuid, name, slug, phone_number, website, country, city)
    VALUES (
        '8a17068c-539a-4ddf-8302-47a6a2c60c92',
        'Travel Pro',
        'travel-pro',
        '+13245678900',
        'https://travelpro.com',
        'United States',
        NULL
    )
    ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        phone_number = EXCLUDED.phone_number,
        website = EXCLUDED.website,
        country = EXCLUDED.country,
        city = EXCLUDED.city
    RETURNING id INTO v_agency_id;

    -- Create or update the OWNER user used to log in from the frontend.
    INSERT INTO users (
        uuid, email, username, password_hash, first_name, last_name,
        date_of_birth, phone_number, role, agency_id, is_active
    )
    VALUES (
        '9c537ec2-1f1f-4096-bb6e-26a85bd50a72',
        v_owner_email,
        v_owner_username,
        v_owner_password_hash,
        'Radislav',
        'Krasnov',
        NULL,
        '+13245678900',
        'OWNER',
        v_agency_id,
        true
    )
    ON CONFLICT (email) DO UPDATE SET
        username = EXCLUDED.username,
        password_hash = EXCLUDED.password_hash,
        first_name = EXCLUDED.first_name,
        last_name = EXCLUDED.last_name,
        date_of_birth = EXCLUDED.date_of_birth,
        phone_number = EXCLUDED.phone_number,
        role = EXCLUDED.role,
        agency_id = EXCLUDED.agency_id,
        is_active = EXCLUDED.is_active
    RETURNING id INTO v_owner_user_id;

    -- Reset only previous thesis QA seed packages for Travel Pro.
    DELETE FROM tour_packages
    WHERE agency_id = v_agency_id
      AND slug IN (
        'tc-excellent-balanced-portugal',
        'tc-moderate-low-margin-prague',
        'tc-bad-unprofitable-iceland',
        'tc-operational-risk-bali',
        'tc-cost-structure-risk-maldives'
      );

    -- Replace previous QA threshold configuration for this agency.
    DELETE FROM analysis_configurations
    WHERE agency_id = v_agency_id
      AND name = 'Thesis QA default thresholds';

    UPDATE analysis_configurations
    SET is_default = false
    WHERE agency_id = v_agency_id;

    INSERT INTO analysis_configurations (
        agency_id, name, min_target_margin_percent, good_margin_percent,
        max_daily_fatigue_score, max_transfer_minutes_per_day, min_buffer_minutes, is_default
    )
    VALUES (v_agency_id, 'Thesis QA default thresholds', 15.00, 25.00, 65, 180, 30, true);

    -- Shared suppliers. Names are deliberately distinct to test supplier concentration.
    INSERT INTO suppliers (agency_id, name, type, contact_email, contact_phone)
    VALUES (v_agency_id, 'QA Hotel Alpha', 'HOTEL', 'groups@hotel-alpha.example', '+351111111')
    ON CONFLICT (agency_id, name) DO UPDATE SET type = EXCLUDED.type
    RETURNING id INTO s_hotel_a;

    INSERT INTO suppliers (agency_id, name, type, contact_email, contact_phone)
    VALUES (v_agency_id, 'QA Hotel Beta', 'HOTEL', 'groups@hotel-beta.example', '+351222222')
    ON CONFLICT (agency_id, name) DO UPDATE SET type = EXCLUDED.type
    RETURNING id INTO s_hotel_b;

    INSERT INTO suppliers (agency_id, name, type, contact_email, contact_phone)
    VALUES (v_agency_id, 'QA Regional Transport', 'TRANSPORT', 'ops@transport.example', '+351333333')
    ON CONFLICT (agency_id, name) DO UPDATE SET type = EXCLUDED.type
    RETURNING id INTO s_transport;

    INSERT INTO suppliers (agency_id, name, type, contact_email, contact_phone)
    VALUES (v_agency_id, 'QA Local Guides Collective', 'GUIDE', 'guides@example.com', '+351444444')
    ON CONFLICT (agency_id, name) DO UPDATE SET type = EXCLUDED.type
    RETURNING id INTO s_guide;

    INSERT INTO suppliers (agency_id, name, type, contact_email, contact_phone)
    VALUES (v_agency_id, 'QA Activity Partners', 'ACTIVITY_PROVIDER', 'booking@activities.example', '+351555555')
    ON CONFLICT (agency_id, name) DO UPDATE SET type = EXCLUDED.type
    RETURNING id INTO s_activity;

    INSERT INTO suppliers (agency_id, name, type, contact_email, contact_phone)
    VALUES (v_agency_id, 'QA Restaurant Network', 'RESTAURANT', 'events@restaurants.example', '+351666666')
    ON CONFLICT (agency_id, name) DO UPDATE SET type = EXCLUDED.type
    RETURNING id INTO s_meal;

    INSERT INTO suppliers (agency_id, name, type, contact_email, contact_phone)
    VALUES (v_agency_id, 'QA Miscellaneous Vendor', 'OTHER', 'admin@misc.example', '+351777777')
    ON CONFLICT (agency_id, name) DO UPDATE SET type = EXCLUDED.type
    RETURNING id INTO s_other;

    INSERT INTO suppliers (agency_id, name, type, contact_email, contact_phone)
    VALUES (v_agency_id, 'QA Single Luxury Resort', 'HOTEL', 'sales@luxury-resort.example', '+960111111')
    ON CONFLICT (agency_id, name) DO UPDATE SET type = EXCLUDED.type
    RETURNING id INTO s_luxury;

    ---------------------------------------------------------------------------
    -- CASE 1: EXCELLENT / BALANCED / PROFITABLE
    -- Expected: LOW financial risk, high quality score, no critical recommendations.
    ---------------------------------------------------------------------------
    INSERT INTO tour_packages (
        agency_id, title, slug, description, destination_country, destination_city,
        duration_days, expected_group_size, selling_price_per_person, currency_code, status, internal_notes
    ) VALUES (
        v_agency_id, 'TC1 Excellent Balanced Portugal Tour', 'tc-excellent-balanced-portugal',
        'Balanced premium Portugal route with diversified suppliers and healthy margin.',
        'Portugal', 'Porto', 4, 12, 1500.00, 'EUR', 'DRAFT',
        'Expected: excellent or good quality, low financial risk, almost no recommendations.'
    ) RETURNING id INTO v_pkg;

    INSERT INTO tour_days (package_id, day_number, title, description, is_rest_day)
    VALUES
      (v_pkg, 1, 'Arrival and Porto orientation', 'Arrival, easy walking tour, welcome dinner.', false),
      (v_pkg, 2, 'Douro Valley culture day', 'Winery, viewpoints, river lunch, moderate transfer.', false),
      (v_pkg, 3, 'Coastal villages and free afternoon', 'Light sightseeing with recovery time.', false),
      (v_pkg, 4, 'Departure', 'Breakfast and airport transfer.', true);

    SELECT id INTO d1 FROM tour_days WHERE package_id = v_pkg AND day_number = 1;
    SELECT id INTO d2 FROM tour_days WHERE package_id = v_pkg AND day_number = 2;
    SELECT id INTO d3 FROM tour_days WHERE package_id = v_pkg AND day_number = 3;
    SELECT id INTO d4 FROM tour_days WHERE package_id = v_pkg AND day_number = 4;

    INSERT INTO itinerary_items (day_id, item_order, type, title, start_time, end_time, duration_minutes, location_name, intensity, is_major_activity)
    VALUES
      (d1, 1, 'TRANSFER', 'Airport transfer to hotel', '09:00', '10:00', 60, 'Porto Airport', NULL, false),
      (d1, 2, 'ACTIVITY', 'Porto old town walking tour', '10:45', '12:30', 105, 'Ribeira', 'MEDIUM', true),
      (d1, 3, 'MEAL', 'Welcome lunch', '12:45', '13:45', 60, 'Local restaurant', NULL, false),
      (d1, 4, 'FREE_TIME', 'Hotel rest and free time', '14:00', '16:00', 120, 'Hotel', NULL, false),
      (d1, 5, 'ACTIVITY', 'Sunset viewpoint visit', '16:30', '18:00', 90, 'Miradouro', 'LOW', false),
      (d2, 1, 'TRANSFER', 'Transfer to Douro Valley', '09:00', '10:30', 90, 'Douro Valley', NULL, false),
      (d2, 2, 'ACTIVITY', 'Winery experience', '11:00', '13:00', 120, 'Winery', 'MEDIUM', true),
      (d2, 3, 'MEAL', 'River lunch', '13:15', '14:15', 60, 'Douro restaurant', NULL, false),
      (d2, 4, 'FREE_TIME', 'Free time near river', '14:30', '16:00', 90, 'Douro riverfront', NULL, false),
      (d2, 5, 'TRANSFER', 'Return to Porto', '16:30', '18:00', 90, 'Porto', NULL, false),
      (d3, 1, 'TRANSFER', 'Short coastal transfer', '09:30', '10:15', 45, 'Matosinhos', NULL, false),
      (d3, 2, 'ACTIVITY', 'Fishing village visit', '10:45', '12:15', 90, 'Coast', 'LOW', true),
      (d3, 3, 'MEAL', 'Seafood lunch', '12:45', '13:45', 60, 'Restaurant', NULL, false),
      (d3, 4, 'FREE_TIME', 'Free afternoon', '14:00', '17:00', 180, 'Porto', NULL, false),
      (d4, 1, 'MEAL', 'Breakfast', '08:30', '09:15', 45, 'Hotel', NULL, false),
      (d4, 2, 'TRANSFER', 'Airport transfer', '10:00', '11:00', 60, 'Porto Airport', NULL, false);

    INSERT INTO cost_items (package_id, supplier_id, category, name, description, cost_type, quantity, unit_cost, currency_code, is_required)
    VALUES
      (v_pkg, s_hotel_a, 'HOTEL', 'Porto hotel nights', '2 nights in Porto hotel', 'PER_PERSON', 2, 95.00, 'EUR', true),
      (v_pkg, s_hotel_b, 'HOTEL', 'Douro hotel night', '1 night in Douro boutique hotel', 'PER_PERSON', 1, 110.00, 'EUR', true),
      (v_pkg, s_transport, 'TRANSPORT', 'Regional minibus', '4 days of local transport', 'PER_DAY', 1, 280.00, 'EUR', true),
      (v_pkg, s_guide, 'GUIDE', 'Local guide', 'Professional guide for 4 days', 'PER_DAY', 1, 220.00, 'EUR', true),
      (v_pkg, s_activity, 'ACTIVITY', 'Included activities', 'Winery, walking tour, coastal visit', 'PER_PERSON', 3, 55.00, 'EUR', true),
      (v_pkg, s_meal, 'MEAL', 'Included meals', '5 included meals', 'PER_PERSON', 5, 32.00, 'EUR', true),
      (v_pkg, s_other, 'INSURANCE', 'Basic travel insurance', 'Basic insurance per traveler', 'PER_PERSON', 1, 28.00, 'EUR', true);

    ---------------------------------------------------------------------------
    -- CASE 2: MODERATE / BORDERLINE MARGIN + SOME ITINERARY PRESSURE
    -- Expected: MEDIUM financial risk, LOW_MARGIN, several itinerary/operational warnings.
    ---------------------------------------------------------------------------
    INSERT INTO tour_packages (
        agency_id, title, slug, description, destination_country, destination_city,
        duration_days, expected_group_size, selling_price_per_person, currency_code, status, internal_notes
    ) VALUES (
        v_agency_id, 'TC2 Moderate Low-Margin Prague Weekend', 'tc-moderate-low-margin-prague',
        'Commercially possible but underpriced weekend with a compressed sightseeing day.',
        'Czech Republic', 'Prague', 3, 10, 1130.00, 'EUR', 'DRAFT',
        'Expected: medium financial risk, low margin recommendation, itinerary recommendations.'
    ) RETURNING id INTO v_pkg;

    INSERT INTO tour_days (package_id, day_number, title, description, is_rest_day)
    VALUES
      (v_pkg, 1, 'Arrival and old town', 'Arrival and short evening tour.', false),
      (v_pkg, 2, 'Compressed Prague highlights', 'Busy day with too many activities and limited rest.', false),
      (v_pkg, 3, 'Departure', 'Breakfast and transfer.', true);

    SELECT id INTO d1 FROM tour_days WHERE package_id = v_pkg AND day_number = 1;
    SELECT id INTO d2 FROM tour_days WHERE package_id = v_pkg AND day_number = 2;
    SELECT id INTO d3 FROM tour_days WHERE package_id = v_pkg AND day_number = 3;

    INSERT INTO itinerary_items (day_id, item_order, type, title, start_time, end_time, duration_minutes, location_name, intensity, is_major_activity)
    VALUES
      (d1, 1, 'TRANSFER', 'Airport transfer', '16:00', '17:00', 60, 'Prague Airport', NULL, false),
      (d1, 2, 'ACTIVITY', 'Evening old town walk', '17:30', '19:00', 90, 'Old Town', 'LOW', true),
      (d1, 3, 'MEAL', 'Welcome dinner', '19:30', '20:30', 60, 'Restaurant', NULL, false),
      (d2, 1, 'TRANSFER', 'Hotel to Castle District', '08:00', '08:45', 45, 'Castle District', NULL, false),
      (d2, 2, 'ACTIVITY', 'Prague Castle tour', '09:00', '11:00', 120, 'Castle', 'MEDIUM', true),
      (d2, 3, 'ACTIVITY', 'Lesser Town guided walk', '11:10', '12:20', 70, 'Lesser Town', 'MEDIUM', true),
      (d2, 4, 'MEAL', 'Quick lunch', '12:25', '13:00', 35, 'Cafe', NULL, false),
      (d2, 5, 'ACTIVITY', 'Jewish Quarter visit', '13:05', '14:35', 90, 'Jewish Quarter', 'MEDIUM', true),
      (d2, 6, 'ACTIVITY', 'River cruise', '14:45', '16:00', 75, 'Vltava', 'LOW', false),
      (d2, 7, 'TRANSFER', 'Return transfer', '16:05', '17:00', 55, 'Hotel', NULL, false),
      (d3, 1, 'MEAL', 'Breakfast', '08:30', '09:00', 30, 'Hotel', NULL, false),
      (d3, 2, 'TRANSFER', 'Airport transfer', '09:30', '10:30', 60, 'Airport', NULL, false);

    INSERT INTO cost_items (package_id, supplier_id, category, name, description, cost_type, quantity, unit_cost, currency_code, is_required)
    VALUES
      (v_pkg, s_hotel_a, 'HOTEL', 'Prague hotel', '3 nights mid-range hotel', 'PER_PERSON', 3, 145.00, 'EUR', true),
      (v_pkg, s_meal, 'MEAL', 'Included meals', '4 included meals', 'PER_PERSON', 4, 38.00, 'EUR', true),
      (v_pkg, s_activity, 'ACTIVITY', 'Paid attractions', 'Castle, museum, cruise', 'PER_PERSON', 3, 70.00, 'EUR', true),
      (v_pkg, s_transport, 'TRANSPORT', 'City transport package', '3 days transport', 'PER_DAY', 1, 300.00, 'EUR', true),
      (v_pkg, s_guide, 'GUIDE', 'Guide', '3 days guiding', 'PER_DAY', 1, 180.00, 'EUR', true),
      (v_pkg, s_other, 'OTHER', 'Booking/admin reserve', 'Internal admin reserve', 'FIXED', 1, 300.00, 'EUR', true);

    ---------------------------------------------------------------------------
    -- CASE 3: BAD / UNPROFITABLE
    -- Expected: CRITICAL financial risk, NEGATIVE_PROFIT, BREAK_EVEN_RISK, low quality cap.
    ---------------------------------------------------------------------------
    INSERT INTO tour_packages (
        agency_id, title, slug, description, destination_country, destination_city,
        duration_days, expected_group_size, selling_price_per_person, currency_code, status, internal_notes
    ) VALUES (
        v_agency_id, 'TC3 Bad Unprofitable Iceland Ring Mini Tour', 'tc-bad-unprofitable-iceland',
        'Attractive itinerary but price is below realistic cost level for small group.',
        'Iceland', 'Reykjavik', 4, 8, 850.00, 'EUR', 'DRAFT',
        'Expected: critical financial risk and negative profit recommendation.'
    ) RETURNING id INTO v_pkg;

    INSERT INTO tour_days (package_id, day_number, title, description, is_rest_day)
    VALUES
      (v_pkg, 1, 'Arrival Reykjavik', 'Arrival and easy city intro.', false),
      (v_pkg, 2, 'Golden Circle', 'Classic day tour.', false),
      (v_pkg, 3, 'South Coast', 'Waterfalls and black sand beach.', false),
      (v_pkg, 4, 'Departure', 'Transfer to airport.', true);

    SELECT id INTO d1 FROM tour_days WHERE package_id = v_pkg AND day_number = 1;
    SELECT id INTO d2 FROM tour_days WHERE package_id = v_pkg AND day_number = 2;
    SELECT id INTO d3 FROM tour_days WHERE package_id = v_pkg AND day_number = 3;
    SELECT id INTO d4 FROM tour_days WHERE package_id = v_pkg AND day_number = 4;

    INSERT INTO itinerary_items (day_id, item_order, type, title, start_time, end_time, duration_minutes, location_name, intensity, is_major_activity)
    VALUES
      (d1, 1, 'TRANSFER', 'Airport transfer', '14:00', '15:00', 60, 'Keflavik', NULL, false),
      (d1, 2, 'ACTIVITY', 'Reykjavik city walk', '16:00', '17:30', 90, 'Reykjavik', 'LOW', true),
      (d1, 3, 'MEAL', 'Dinner', '18:30', '19:30', 60, 'Restaurant', NULL, false),
      (d2, 1, 'TRANSFER', 'Golden Circle transfer', '08:30', '10:00', 90, 'Thingvellir', NULL, false),
      (d2, 2, 'ACTIVITY', 'National park and geysers', '10:30', '13:00', 150, 'Golden Circle', 'MEDIUM', true),
      (d2, 3, 'MEAL', 'Lunch', '13:15', '14:00', 45, 'Cafe', NULL, false),
      (d2, 4, 'ACTIVITY', 'Gullfoss waterfall', '14:30', '16:00', 90, 'Gullfoss', 'LOW', true),
      (d2, 5, 'TRANSFER', 'Return to hotel', '16:30', '18:00', 90, 'Reykjavik', NULL, false),
      (d3, 1, 'TRANSFER', 'South Coast transfer', '08:00', '10:00', 120, 'South Coast', NULL, false),
      (d3, 2, 'ACTIVITY', 'Waterfalls route', '10:30', '13:00', 150, 'Skogafoss', 'MEDIUM', true),
      (d3, 3, 'MEAL', 'Lunch', '13:15', '14:00', 45, 'Cafe', NULL, false),
      (d3, 4, 'ACTIVITY', 'Black sand beach', '14:30', '16:00', 90, 'Reynisfjara', 'MEDIUM', true),
      (d3, 5, 'TRANSFER', 'Return to Reykjavik', '16:30', '19:00', 150, 'Reykjavik', NULL, false),
      (d4, 1, 'TRANSFER', 'Airport transfer', '09:00', '10:00', 60, 'Keflavik', NULL, false);

    INSERT INTO cost_items (package_id, supplier_id, category, name, description, cost_type, quantity, unit_cost, currency_code, is_required)
    VALUES
      (v_pkg, s_hotel_a, 'HOTEL', 'Iceland hotel', '3 nights hotel', 'PER_PERSON', 3, 180.00, 'EUR', true),
      (v_pkg, s_meal, 'MEAL', 'Meals', '4 included meals', 'PER_PERSON', 4, 55.00, 'EUR', true),
      (v_pkg, s_activity, 'ACTIVITY', 'Activities and entries', '3 paid activity bundles', 'PER_PERSON', 3, 95.00, 'EUR', true),
      (v_pkg, s_transport, 'TRANSPORT', 'Private vehicle', 'Small-group vehicle rental and fuel', 'PER_GROUP', 1, 1100.00, 'EUR', true),
      (v_pkg, s_guide, 'GUIDE', 'Specialized Iceland guide', '3 guiding days', 'PER_DAY', 1, 220.00, 'EUR', true);

    ---------------------------------------------------------------------------
    -- CASE 4: PROFITABLE BUT OPERATIONALLY UNREALISTIC / CRITICAL FATIGUE
    -- Expected: LOW financial risk but CRITICAL fatigue, operational recommendations.
    ---------------------------------------------------------------------------
    INSERT INTO tour_packages (
        agency_id, title, slug, description, destination_country, destination_city,
        duration_days, expected_group_size, selling_price_per_person, currency_code, status, internal_notes
    ) VALUES (
        v_agency_id, 'TC4 Operational Risk Bali Adventure', 'tc-operational-risk-bali',
        'Profitable package with unrealistic early starts, long transfers, short buffers and critical fatigue.',
        'Indonesia', 'Bali', 5, 12, 1600.00, 'EUR', 'DRAFT',
        'Expected: good margin but poor itinerary/operational feasibility.'
    ) RETURNING id INTO v_pkg;

    INSERT INTO tour_days (package_id, day_number, title, description, is_rest_day)
    VALUES
      (v_pkg, 1, 'Overloaded temple and volcano day', 'Too much in one day.', false),
      (v_pkg, 2, 'Another intensive adventure day', 'High fatigue repeated.', false),
      (v_pkg, 3, 'Cultural recovery day', 'Moderate day.', false),
      (v_pkg, 4, 'Beach free time', 'Rest day.', true),
      (v_pkg, 5, 'Departure', 'Departure transfer.', true);

    SELECT id INTO d1 FROM tour_days WHERE package_id = v_pkg AND day_number = 1;
    SELECT id INTO d2 FROM tour_days WHERE package_id = v_pkg AND day_number = 2;
    SELECT id INTO d3 FROM tour_days WHERE package_id = v_pkg AND day_number = 3;
    SELECT id INTO d4 FROM tour_days WHERE package_id = v_pkg AND day_number = 4;
    SELECT id INTO d5 FROM tour_days WHERE package_id = v_pkg AND day_number = 5;

    INSERT INTO itinerary_items (day_id, item_order, type, title, start_time, end_time, duration_minutes, location_name, intensity, is_major_activity)
    VALUES
      (d1, 1, 'TRANSFER', 'Pre-dawn transfer to volcano', '05:30', '08:30', 180, 'Mount Batur', NULL, false),
      (d1, 2, 'ACTIVITY', 'Volcano hike', '08:30', '10:00', 90, 'Mount Batur', 'HIGH', true),
      (d1, 3, 'TRANSFER', 'Transfer to temple area', '10:00', '12:00', 120, 'Temple route', NULL, false),
      (d1, 4, 'ACTIVITY', 'Temple complex tour', '12:00', '14:00', 120, 'Besakih', 'HIGH', true),
      (d1, 5, 'TRANSFER', 'Transfer to waterfall', '14:00', '16:00', 120, 'Waterfall', NULL, false),
      (d1, 6, 'ACTIVITY', 'Waterfall trek', '16:00', '18:00', 120, 'Waterfall', 'HIGH', true),
      (d1, 7, 'ACTIVITY', 'Evening market walk', '18:00', '20:00', 120, 'Market', 'HIGH', true),
      (d1, 8, 'ACTIVITY', 'Night cultural show', '20:00', '22:30', 150, 'Ubud', 'HIGH', true),
      (d2, 1, 'TRANSFER', 'Early transfer to rafting base', '06:00', '08:30', 150, 'Rafting base', NULL, false),
      (d2, 2, 'ACTIVITY', 'White-water rafting', '08:30', '11:00', 150, 'River', 'HIGH', true),
      (d2, 3, 'TRANSFER', 'Transfer to cycling route', '11:00', '12:30', 90, 'Cycling route', NULL, false),
      (d2, 4, 'ACTIVITY', 'Mountain cycling', '12:30', '15:00', 150, 'Kintamani', 'HIGH', true),
      (d2, 5, 'ACTIVITY', 'Village walk', '15:00', '17:00', 120, 'Village', 'MEDIUM', true),
      (d2, 6, 'TRANSFER', 'Return to hotel', '17:00', '20:00', 180, 'Hotel', NULL, false),
      (d3, 1, 'ACTIVITY', 'Cooking class', '10:00', '12:00', 120, 'Ubud', 'LOW', true),
      (d3, 2, 'MEAL', 'Lunch', '12:15', '13:15', 60, 'Cooking school', NULL, false),
      (d3, 3, 'FREE_TIME', 'Free afternoon', '13:30', '17:00', 210, 'Ubud', NULL, false),
      (d4, 1, 'FREE_TIME', 'Beach free day', '10:00', '17:00', 420, 'Beach', NULL, false),
      (d5, 1, 'TRANSFER', 'Airport transfer', '10:00', '11:30', 90, 'Airport', NULL, false);

    INSERT INTO cost_items (package_id, supplier_id, category, name, description, cost_type, quantity, unit_cost, currency_code, is_required)
    VALUES
      (v_pkg, s_hotel_a, 'HOTEL', 'Bali hotels', '4 nights', 'PER_PERSON', 4, 100.00, 'EUR', true),
      (v_pkg, s_meal, 'MEAL', 'Meals', '4 included meals', 'PER_PERSON', 4, 35.00, 'EUR', true),
      (v_pkg, s_activity, 'ACTIVITY', 'Adventure activities', '5 major activities', 'PER_PERSON', 5, 50.00, 'EUR', true),
      (v_pkg, s_transport, 'TRANSPORT', 'Private transport', '5 days transport', 'PER_DAY', 1, 500.00, 'EUR', true),
      (v_pkg, s_guide, 'GUIDE', 'Guide', '5 guide days', 'PER_DAY', 1, 200.00, 'EUR', true);

    ---------------------------------------------------------------------------
    -- CASE 5: PROFITABLE BUT BAD COST STRUCTURE
    -- Expected: LOW financial risk but supplier dependency, hotel dominance, OTHER cost warning.
    ---------------------------------------------------------------------------
    INSERT INTO tour_packages (
        agency_id, title, slug, description, destination_country, destination_city,
        duration_days, expected_group_size, selling_price_per_person, currency_code, status, internal_notes
    ) VALUES (
        v_agency_id, 'TC5 Cost Structure Risk Maldives Luxury', 'tc-cost-structure-risk-maldives',
        'High-margin luxury product with excessive dependency on one resort and opaque OTHER costs.',
        'Maldives', 'Male', 5, 10, 4000.00, 'EUR', 'DRAFT',
        'Expected: low financial risk but cost-structure recommendations.'
    ) RETURNING id INTO v_pkg;

    INSERT INTO tour_days (package_id, day_number, title, description, is_rest_day)
    VALUES
      (v_pkg, 1, 'Arrival and resort transfer', 'Arrival, seaplane, check-in.', false),
      (v_pkg, 2, 'Resort leisure', 'Light activities and free time.', true),
      (v_pkg, 3, 'Snorkeling and spa', 'Balanced premium experience.', false),
      (v_pkg, 4, 'Private island day', 'Relaxed day.', true),
      (v_pkg, 5, 'Departure', 'Transfer to airport.', true);

    SELECT id INTO d1 FROM tour_days WHERE package_id = v_pkg AND day_number = 1;
    SELECT id INTO d2 FROM tour_days WHERE package_id = v_pkg AND day_number = 2;
    SELECT id INTO d3 FROM tour_days WHERE package_id = v_pkg AND day_number = 3;
    SELECT id INTO d4 FROM tour_days WHERE package_id = v_pkg AND day_number = 4;
    SELECT id INTO d5 FROM tour_days WHERE package_id = v_pkg AND day_number = 5;

    INSERT INTO itinerary_items (day_id, item_order, type, title, start_time, end_time, duration_minutes, location_name, intensity, is_major_activity)
    VALUES
      (d1, 1, 'TRANSFER', 'Seaplane transfer', '11:00', '12:00', 60, 'Resort', NULL, false),
      (d1, 2, 'MEAL', 'Lunch', '13:00', '14:00', 60, 'Resort', NULL, false),
      (d1, 3, 'FREE_TIME', 'Resort free time', '14:00', '18:00', 240, 'Resort', NULL, false),
      (d2, 1, 'FREE_TIME', 'Beach day', '10:00', '17:00', 420, 'Resort', NULL, false),
      (d3, 1, 'ACTIVITY', 'Snorkeling tour', '10:00', '12:00', 120, 'Reef', 'LOW', true),
      (d3, 2, 'MEAL', 'Lunch', '12:30', '13:30', 60, 'Resort', NULL, false),
      (d3, 3, 'FREE_TIME', 'Spa and free time', '14:00', '17:00', 180, 'Resort', NULL, false),
      (d4, 1, 'FREE_TIME', 'Private island leisure', '10:00', '17:00', 420, 'Island', NULL, false),
      (d5, 1, 'TRANSFER', 'Airport transfer', '10:00', '11:00', 60, 'Airport', NULL, false);

    INSERT INTO cost_items (package_id, supplier_id, category, name, description, cost_type, quantity, unit_cost, currency_code, is_required)
    VALUES
      (v_pkg, s_luxury, 'HOTEL', 'Single resort accommodation', '5 nights at one luxury resort', 'PER_PERSON', 5, 320.00, 'EUR', true),
      (v_pkg, s_transport, 'TRANSPORT', 'Seaplane transfers', 'Group seaplane logistics', 'PER_GROUP', 1, 1800.00, 'EUR', true),
      (v_pkg, s_meal, 'MEAL', 'Premium meal plan', 'Included meal package', 'PER_PERSON', 5, 30.00, 'EUR', true),
      (v_pkg, s_activity, 'ACTIVITY', 'Snorkeling and spa', 'Premium activities', 'PER_PERSON', 2, 120.00, 'EUR', true),
      (v_pkg, s_other, 'OTHER', 'Opaque resort service bundle', 'Unclassified resort fees and handling costs', 'PER_GROUP', 1, 8000.00, 'EUR', true),
      (v_pkg, s_guide, 'GUIDE', 'Local coordination', 'On-site coordinator', 'PER_GROUP', 1, 1000.00, 'EUR', true);

END $$;

-- Show generated package UUIDs for API testing.
SELECT
    id,
    agency_id,
    uuid,
    slug,
    title,
    expected_group_size,
    selling_price_per_person,
    currency_code
FROM tour_packages
WHERE slug IN (
    'tc-excellent-balanced-portugal',
    'tc-moderate-low-margin-prague',
    'tc-bad-unprofitable-iceland',
    'tc-operational-risk-bali',
    'tc-cost-structure-risk-maldives'
)
ORDER BY slug;

-- Optional: after running POST /tour-packages/:uuid/analyze, inspect latest results.
-- SELECT tp.slug, far.gross_margin_percent, far.gross_profit, psr.overall_score, psr.profitability_score,
--        psr.itinerary_balance_score, psr.operational_feasibility_score, psr.cost_structure_score,
--        par.analysis_status, par.created_at
-- FROM tour_packages tp
-- JOIN package_analysis_runs par ON par.package_id = tp.id
-- JOIN financial_analysis_results far ON far.analysis_run_id = par.id
-- JOIN package_score_results psr ON psr.analysis_run_id = par.id
-- WHERE tp.slug LIKE 'tc-%'
-- ORDER BY tp.slug, par.created_at DESC;
